# Generated by Django 5.2.8 on 2025-11-25 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_site', models.CharField(max_length=100, verbose_name='Nome do Site')),
                ('logo_do_site', models.ImageField(upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'svg', 'png', 'jpg', 'jpeg'])], verbose_name='Logo do Site')),
                ('texto_chamada', models.TextField(verbose_name='Texto da Chamada (Hero)')),
                ('texto_sobre', models.TextField(verbose_name='Texto Sobre Nós')),
                ('imagem_sobre', models.ImageField(upload_to='sobre/', verbose_name='Imagem da Seção Sobre')),
                ('endereco', models.TextField(verbose_name='Endereço Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail de Contato')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='Número do WhatsApp')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da Página',
                'verbose_name_plural': 'Configurações da Página',
            },
        ),
    ]
